[package]
name = "my-automation-project"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["scrapper"]

[dependencies]
tokio = { version = "1", features = ["full"] }
lettre = "0.10.0-rc.4"
scrapper ={ path = "./scrapper"}
dotenv = "0.15.0"
